baseURL = 'https://moon.daytheipc.com/'
languageCode = 'en-us'
title = "Daniela's Hideout"
theme = 'day'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[params]
onionBaseURL = 'http://dayos4s5ipb5iorxo7nx2yfch4obxlxyg26wsoxp3ungezgfwlzr2oyd.onion/'