title = "Website Name"
baseURL = 'https://example.org'
languageCode = 'en-us'
onionBaseURL = ""

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true
